### PR TITLE
Release 12.2.3

### PR DESCRIPTION
**Pull request by prithivraj**
* Fixed issue in help center where it did not obey the setting to have at most one open conversation.
* Fixed issues with status bar height on Android 12.
* Fixed issue with truncating expected time on the home screen.
* Improved performance of push notifications
* Intercom now uses Coil 2.0

### CODE REVIEW

**Comment by KrunalStrategyX** [comment]
Hi @prithivraj I have update intercom lib new version (12.2.2 -> 12.2.3) after it give below error

image


How can i resolve that because i have already initialized Intercom.initialize() in my application class 

image


Also When I was used older version of library (12.2.2) it work but when i upload any picture in intercom conversation that time app was crash and firebase is get below error code.

image

**Comment by VinuPolly-Bonnet** [comment]
Hi @prithivraj I am facing the same issue as @KrunalStrategyX , I was updating the library from 12.1.1 -> 12.2.3, but the error log says to initialise in the onCreate of the Application class, but I have been already doing that since the start.
`com.google.firebase:firebase-bom:29.2.0` -> Firebase version
`implementation 'io.intercom.android:intercom-sdk:12.2.3'` -> Intercom Version

Error Log
----------
`java.lang.RuntimeException: Unable to create application com.bonnet.App: io.intercom.android.sdk.exceptions.IntercomIntegrationException: Intercom was not initialized correctly, Intercom.initialize() needs to be called in onCreate() in your Application class.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6991)
        at android.app.ActivityThread.access$1700(ActivityThread.java:274)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: io.intercom.android.sdk.exceptions.IntercomIntegrationException: Intercom was not initialized correctly, Intercom.initialize() needs to be called in onCreate() in your Application class.
        at io.intercom.android.sdk.Injector.get(Injector.java:129)
        at io.intercom.android.sdk.Intercom$Companion.initialize(Intercom.kt:559)
        at com.bonnet.App.onCreate(App.kt:55)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6986)`

App.kt
-------
`override fun onCreate() {
        super.onCreate()
        context = this

        if (BuildConfig.DEBUG) {
            Timber.plant(Timber.DebugTree())
            Analytics.register(TimberAnalyticsCore())
        } else {
            Timber.plant(CrashlyticsTree())
            Analytics.register(FirebaseCrashlyticsCore())
            Analytics.register(FirebaseAnalyticsCore(this))
        }

        component = createAppComponent()

        JodaTimeAndroid.init(this)

        // Intercom.setLogLevel(Intercom.LogLevel.VERBOSE)
        Intercom.initialize(this, BuildConfig.INTERCOM_ANDROID_API_KEY, BuildConfig.INTERCOM_APP_ID)
        Intercom.client().setBottomPadding(resources.getDimensionPixelSize(R.dimen.bottom_padding_intercom))

        val preferences = PreferenceManager.getDefaultSharedPreferences(this)
        Error.configure(object: Config.Base(this, BuildConfig.DEBUG) {
            override val shouldAddErrorId: Boolean
                get() = preferences.getBoolean(PreferencesDao.SHOW_ERROR_CODES, false)
        })

        Pusher.start(this, BuildConfig.PUSHER_INSTANCE_ID)

        RxJavaPlugins.setErrorHandler { e: Throwable ->
            var cause: Throwable? = null
            if (e is UndeliverableException) {
                cause = e.cause!!
            }
            cause?.let {
                if (it is FirebaseNetworkException) {
                    Timber.e(it, "Firebase UndeliverableException caught globally")
                    // fine, irrelevant network problem or API that throws on cancellation
                    return@setErrorHandler
                }
            }
        }
    }`

**Comment by prithivraj** [comment]
@KrunalStrategyX @VinuPolly-Bonnet 

That was a bug on our end. Thank you for reporting. 
Please upgrade to 12.3.0 and let us know if it works. 
Thanks!

**Comment by KrunalStrategyX** [comment]
Hey @prithivraj I have update intercom lib new version (12.2.2 -> 12.3.0) it's work ok but second issue is still not resolve the issue is when i was upload any photo in intercom chat that time app crash and firebase give below error

image

Please check this one try to find solution.

**Comment by KrunalStrategyX** [comment]
> Hey @prithivraj I have update intercom lib new version (12.2.2 -> 12.3.0) it's work ok but second issue is still not resolve the issue is when i was upload any photo in intercom chat that time app crash and firebase give below error
> 
> image
> 
> Please check this one.

Hi @KarthikMS and @prithivraj Are you resolve this error ?
can you have find solution for this error.

**Comment by KrunalStrategyX** [comment]
> > Hey @prithivraj I have update intercom lib new version (12.2.2 -> 12.3.0) it's work ok but second issue is still not resolve the issue is when i was upload any photo in intercom chat that time app crash and firebase give below error
> > image
> > Please check this one.
> 
> Hi @KarthikMS and @prithivraj Are you resolve this error ? can you have find solution for this error.

Hi @KarthikMS and @prithivraj can you find this issue

**Comment by prithivraj** [comment]
@KrunalStrategyX Please reach out to our support using the messenger in https://www.intercom.com/

**Pull request merged**
